var gitUser = [{
  "login": "jacksaintjack",
  "id": 9700459,
  "avatar_url": "https://avatars.githubusercontent.com/u/9700459?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/jacksaintjack",
  "html_url": "https://github.com/jacksaintjack",
  "followers_url": "https://api.github.com/users/jacksaintjack/followers",
  "following_url": "https://api.github.com/users/jacksaintjack/following{/other_user}",
  "gists_url": "https://api.github.com/users/jacksaintjack/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/jacksaintjack/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/jacksaintjack/subscriptions",
  "organizations_url": "https://api.github.com/users/jacksaintjack/orgs",
  "repos_url": "https://api.github.com/users/jacksaintjack/repos",
  "events_url": "https://api.github.com/users/jacksaintjack/events{/privacy}",
  "received_events_url": "https://api.github.com/users/jacksaintjack/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Nicholas Glover",
  "company": "1989",
  "blog": "",
  "location": "United States",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-11-12T17:40:45Z",
  "updated_at": "2015-05-21T19:47:44Z"
}]
